# Generated by Django 4.1.3 on 2023-09-09 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='numero_respuestas',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tema',
            name='contexto',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
