# Generated by Django 4.1.3 on 2023-09-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_busqueda_numero_respuestas_tema_contexto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='es_acoso',
        ),
    ]
